# -*- coding: utf-8 -*-
"""NumberGuessingAI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sH-VunJV3L9GaBJz3jlIOHiP1pDDyc_M
"""

import random
 
minimum = 1
maximum = 100
answer = ""
playing = ""
 
number = random.randint(minimum,maximum)
 
while playing != "no":
  while answer != "yes":
    print("Is" + str(number)  + "your number?")
    print("Answer with yes, low, or high.")
    answer = input()
 
    if answer == "high":
      maximum = number-1
      number = random.randint(minimum,maximum)
    elif answer == "low":
      minimum = number+1
      number = random.randint(minimum,maximum) 
    elif answer == "yes":
      print("I guessed right! Do you want to play again? Answer with yes or no.")
      answer = ""
      playing = input()
      if playing == "no":
        break
      continue
    else:
      print("Please answer correctly.")
      continue